name = "sitcon-shortlinks"
main = "worker.ts"
compatibility_date = "2025-11-25"

routes = [
  { pattern = "sitcon.org/*", zone_name = "sitcon.org" },
  { pattern = "i.sitcon.org/*", zone_name = "sitcon.org" }
]